name: Build Docset

on:
  push:
  pull_request:
  create:
    tags:
      - "v*"

env:
  DOCSET_NAME: Linux_Man_Pages
  LINUX_VERSION: "6.05"
  LINUX_SRC: "https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/"
  # It's not possible to access env in the same environment https://github.community/t/how-to-use-env-context/16975/2
  LINUX_FILE: 'man-pages-$LINUX_VERSION.tar.xz'
  POSIX_VERSION: "2017"
  POSIX_SRC: "https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/man-pages-posix/"
  # It's not possible to access env in the same environment https://github.community/t/how-to-use-env-context/16975/2
  POSIX_FILE: 'man-pages-posix-$POSIX_VERSION-a.tar.xz'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Runs a single command using the runners shell
      - name: Install deps
        run: sudo apt update &&
          sudo apt install -y
          man2html
          wget
          zip

      # Runs a set of commands using the runners shell
      - name: Download and unpack Linux man-pages
        run: |
            wget -nv "$LINUX_SRC/${{env.LINUX_FILE}}"
            tar xvf ${{env.LINUX_FILE}}

      - name: Download and unpack POSIX man-pages
        run: |
            wget -nv "$POSIX_SRC/${{env.POSIX_FILE}}"
            tar xvf ${{env.POSIX_FILE}}

      - name: Build
        run: python3 mandocset.py -o $DOCSET_NAME -p man-pages-$LINUX_VERSION man-pages-posix-$POSIX_VERSION -i etc/tux.png -I etc/tux@2x.png

      - name: Pack
        run: zip -r $DOCSET_NAME.docset.zip $DOCSET_NAME.docset

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux-man-pages-docset
          path: |
            ${{ env.DOCSET_NAME }}.docset.zip

      - name: Prerelease
        if: startsWith(github.ref, 'refs/tags/') && ( contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') )
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.DOCSET_NAME }}.docset.zip
          prerelease: true
          draft: true
          body: Docset for Linux man-pages ${{ env.LINUX_VERSION }} with man-pages-posix ${{ env.POSIX_VERSION }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/') && ! ( contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') )
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.DOCSET_NAME }}.docset.zip
          draft: true
          body: Docset for Linux man-pages ${{ env.LINUX_VERSION }} with man-pages-posix ${{ env.POSIX_VERSION }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
